### ISSUE TITLE
About the LDR dataset.

### ISSUE THREAD

**Issue by csqiangwen** [Hans1984/GlowGAN#1]
Thanks for your great work! Could you provide the LDR dataset for training? It will be pretty helpful.

**Comment by Hans1984** [comment]
Thank you for your attention! You can download from https://drive.google.com/file/d/1IrIIHNdx_-CU3_G1D6Aqesvb95CsCDGV/view?usp=drive_link. If you wanna more, we highly suggest to download from instagram, flickr ...
